### ISSUE TITLE
Need some local dev docs!

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#108]
In particular, I am having a tough time figuring out how to set up a verifier. The default browserid-verifier set up to listen on port 5050 recieves the assertion and returns the following error:

> [2014-07-16 16:01:13] bid.v2.INFO: verify { result: 'failure',
  reason: '127.0.0.1:9000 is not a browserid primary: Error: socket hang up',
  rp: 'http://127.0.0.1:9010' }

**Comment by rfk** [comment]
IIUC we've solved this via fxa-local-dev, and any further docs on local development should be part of a broader strategy involving that repo.  Closing this out.
