### ISSUE TITLE
formatting of args %s is not being done in production

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#118]
I was looking at stage logs and noticed that format flags, e.g., `%s`, `%2j`, are not being evaluated. 

For example:

{"level":20,"levelname":"VERBOSE","hostname":"ip-10-93-171-32","name":"fxa.server","op":"fxa.server","pid":3362,"time":"2014-08-14T03:02:44.699Z","v":1,"args":["Response: %:2j <%s>",{"name":"123done-stage","image_uri":"https://123done-stage.dev.lcip.org/img/logo@2x.png","redirect_uri":"https://123done-stage.dev.lcip.org/api/oauth"},"1407985364692-3362-49637"]}

Or, exploded with python -m json.tool: 
```
{
    "args": [
        "Response: %:2j <%s>",
        {
            "image_uri": "https://123done-stage.dev.lcip.org/img/logo@2x.png",
            "name": "123done-stage",
            "redirect_uri": "https://123done-stage.dev.lcip.org/api/oauth"
        },
        "1407985364692-3362-49637"
    ],
    "hostname": "ip-10-93-171-32",
    "level": 20,
    "levelname": "VERBOSE",
    "name": "fxa.server",
    "op": "fxa.server",
    "pid": 3362,
    "time": "2014-08-14T03:02:44.699Z",
    "v": 1
}
```

**Comment by seanmonstar** [comment]
I believe this is done with the use of mozlog.
