### ISSUE TITLE
Make the Basket API a FxA OAuth service provider

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#126]
The [Basket API](https://github.com/mozilla/basket) is provided by the Mozilla's engagement team to manage various newsletter subscriptions. Integration with FxA is currently being done: https://bugzilla.mozilla.org/show_bug.cgi?id=1041074 

Basket has it's own methods of authenticating requests (via tokens), but after chatting with @pmclanahan, we decided it makes sense to have Basket be a FxA OAuth service provider, meaning it would have it's own scope, e.g., "basket", that FxA reliers could request a scope for. I suspect this scope would be limited to FxA front end code for the time being, e.g., for users to manage/subscribe to a newsletter as part of the signup flow.

Actions here are to provision Basket as a service provider (define scopes, limit them to certain client_ids, etc.) and document what Basket needs to do to integrate with FxA (how to verify tokens, etc.).

**Comment by rfk** [comment]
We're working towards this with the current basket-proxy-server setup, I don't think there's useful context here that's not already covered in basket bugzilla bugs.  Closing.
