### ISSUE TITLE
Tests for generate-client.js

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#135]
Does @ckolos use [generate-client.js](https://github.com/mozilla/fxa-oauth-server/blob/master/scripts/generate-client.js) to generate new clients? If so, I consider it part of our prod infrastructure and it needs tests.

**Comment by rfk** [comment]
@seanmonstar is this all obsoleted by the new client-management API?

**Comment by seanmonstar** [comment]
I guess so. That script still exists, but it's not the way we'll be moving forward here...

**Comment by rfk** [comment]
Great, imma close this out
