### ISSUE TITLE
Update client configuration documentation

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#137]
https://github.com/mozilla/fxa-oauth-server/blob/master/docs/clients.md could use a refresh.

Is https://github.com/mozilla/fxa-oauth-server/blob/master/scripts/generate-client.js the preferred way of generating OAuth credentials? If so, we need to update the above documentation on how to use it properly.

**Comment by rfk** [comment]
@seanmonstar took care of this, closing...
