### ISSUE TITLE
Add MakeDrive as a service provider

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#141]
[MakeDrive](https://wiki.mozilla.org/Webmaker/MakeDrive) is a an offline-first, syncing filesystem for the web and Webmaker.

I had a chat with the MakeDrive team and they are interested in making MakeDrive a FxA Service Provider.

The end goal would be for a user to log in to Webmaker with FxA and have her requests from the Webmaker client app to MakeDrive be authenticated with FxA OAuth tokens. 

I think this amounts to adding a `makedrive` scope to the list of known scopes.

**Comment by rfk** [comment]
@ckarlof is this still a thing we need to be tracking on our end?

**Comment by ckarlof** [comment]
Haven't heard from them since.
