### ISSUE TITLE
CLI tool for acquiring OAuth tokens in dev environment

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#142]
It's become apparent that getting "test tokens" is not exactly straightforward for non-core devs. 

I propose a CLI tool takes email, password, and scopes and returns a token using a `canGrant` client_id. It should probably be pointed at the dev server (latest or nightly). 

A good starting place would be to adapt https://github.com/edmoz/fxa-sync-client, which uses @zaach's https://github.com/zaach/node-fx-sync.

**Comment by rfk** [comment]
I'm pretty sure this is describing @seanmonstar's oauth client, assigning to him for triage

**Comment by rfk** [comment]
We have such a thing, closing this out
