### ISSUE TITLE
Restrict and document scopes that can be requested

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#143]
If a whitelisted relier requests an unknown scope (e.g.a typo), it could be frustrating debugging experience why it doesn't work. In addition to `profile`, we got three others in the pipeline now: `basket`, `makedrive`, and `galaxy`.

**Comment by vladikoff** [comment]
got here via triage, what should we do about this @rfk ?

**Comment by rfk** [comment]
Let's revisit this as part of oauth/openid-connect work in Q4; hearting

**Comment by jwhitlock** [comment]
I got hit by this today, would love to see a documented list of scopes, and an endpoint that advertises them (like #257).

Ones that don't work (result ing errno 109, "Invalid request parameter"):
* ``profile`` (once upon a time it worked)

Ones that work:
* ``profile:email``
* ``profile:avatar``

Others?

**Comment by rfk** [comment]
> profile (once upon a time it worked)

@jwhitlock this seems to be because you're marked as an "untrusted" client (i.e. one that's not hosted by Mozilla) which restricts the scopes that you can request.  I'm surprised that "profile" scope ever worked in this configuration.

**Comment by jwhitlock** [comment]
It was working February 2015, probably before the trusted/untrusted distinction.

**Comment by rfk** [comment]
Ah, indeed, that distinction would have come in around March/April 2015.  Thanks for clarifying!
