### ISSUE TITLE
Consider using lout to generate API docs

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-oauth-server#153]
The [lout](https://github.com/hapijs/lout) can generate a `/docs` endpoint that automatically documents all other endpoints. It includes the request parameters, all of their validation rules, and the response schemas. By adding a `description` and `tags` properties to each route, it will also include the extra information we'd be writing in the `API.md` file.

The win: docs don't get out of sync. Adding a property, or anything similar, will mean the docs are updated. And each installation will have its own docs, located at `/docs` (configurable), so people can know what is the state at each stage in our development cycle.

The lose: there's a new endpoint on our servers, run by code that we haven't written nor reviewed. I can assume it's used by Walmart, but still, danger?

@ckarlof @dannycoates considered this for the fxa-auth-server before?

**Comment by rfk** [comment]
This has been on the backburner long enough that I'm just going to close it WONTFIX
