### ISSUE TITLE
improve `grunt release` to bump version

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-oauth-server#159]

**Comment by rishibaldawa** [comment]
Something like [grunt-bump](https://github.com/geddski/grunt-release) or [grunt-release](https://github.com/geddski/grunt-release) ?

**Comment by seanmonstar** [comment]
Oh nice, grunt-release looks perfect.

**Comment by rishibaldawa** [comment]
I have some time this weekend. Will try to get something working.

**Comment by pdehaan** [comment]
FWIW, we're using **grunt-bump** for the [**fxa-content-server**](https://github.com/mozilla/fxa-content-server/blob/7c38abe5093c5c43b1d2d1c29bade2c79f542730/package.json#L78) and [**fxa-auth-server**](https://github.com/mozilla/fxa-auth-server/blob/master/package.json#L51) repos. /cc @jrgm

**Comment by rishibaldawa** [comment]
using the same thing everywhere makes much more sense to me, so I'd prefer to start with grunt-bump. If grunt-bump doesn't suit all usecases, then migrating all to grunt-release later would be easier. Let me know what you think.

**Comment by rfk** [comment]
:+1: to consistency
