### ISSUE TITLE
CLI tool for managing OAuth configurations

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#170]
Currently, it's a PITA for @ckolos to update OAuth configurations in production. We can make this process significantly easier if we:

* release the OAuth management config to production
* make a command time tool that @ckolos can use to update these configurations from a bastion host

Security is of course a concern here. I'll add some thoughts later when I have time.

**Comment by seanmonstar** [comment]
This was done last quarter.
