### ISSUE TITLE
alert when clients are changed

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-oauth-server#174]
We want to receive an email alert every time one of the client management routes are accessed, include the client, method, uri, and user who accessed it.

**Comment by vladikoff** [comment]
@seanmonstar do we still need this at this time, while we have the api on the internal server?

**Comment by seanmonstar** [comment]
@vladikoff I cannot for the life of me remember the **why** here. Though, it's quite simple to add an alert since there's logs, right?

**Comment by vladikoff** [comment]
"an email alert every time one of the client management routes are accessed"

We still only have this in development mode. Let's reopen this once we use the client management endpoints in production
