### ISSUE TITLE
GET /v1/client/:id does not return 'whitelisted'

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#176]
Currently the response for GET client/:id is
```
id: "0fddc2b28f47c2d7"
image_uri: "https://marketplace-dev.mozflare.net/media/img/mkt/logos/128.png"
name: "Find My Device Dev"
redirect_uri: "http://fmd.dev.mozaws.net/oauth"
```
Should that also include `whitelisted: false` or `true`?
I can add a PR to this.

**Comment by rfk** [comment]
It now returns the new "trusted" property, since we used this for the pocket integration.  Closing this out.
