### ISSUE TITLE
Provide a mechanism for reliers to learn when the user last authenticated with the auth server

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#181]
Some reliers need to know at what time the user last successfully entered her password. E.g., if a user on Marketplace enters her purchase PIN incorrectly too many times in a row, they force her to re-enter her password to reset the PIN. This "last authentication time" needs to be communicated to Marketplace in some manner (https://bugzilla.mozilla.org/show_bug.cgi?id=1104304). 

Luckily, the FxA auth server includes this time in signed certs (https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-12). 

It's not clear what is the best way to communicate it to Marketplace, but a simple one would be to return the `authAt` value in the [the response from the OAuth server when the relier exchanges a code for a token](https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#post-v1token). 

**Include the time in the response when  https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#post-v1token

**Comment by ckarlof** [comment]
@rfk, can you look into this when you get back? Kumar from Payments feels like this (server validation of last user authentication) is required before they can use `action=force_auth`.

**Comment by seanmonstar** [comment]
@ckarlof so, if we record the timestamp when we generate a token to give to Marketplace, that won't necessarily stay updated. They could sign into Markplace on Jan 1, and that's the time we would record. Perhaps Jan 20th, they did an action needing a re-auth, and Marketplace asks us the lastAuthAt value, we'd say Jan 1. Even if the user happily logged in and fiddled with their avatar earlier that day.

**Comment by ckarlof** [comment]
@seanmonstar, the idea is that we record the value of fxa-lastAuthAt in the assertion provided from the user agent (not the time we generated the token). This is the time that the user provided her password to the auth server.

**Comment by seanmonstar** [comment]
@ckarlof I know. But we can only really record that value when a token is
generated. The user may have provided their password to the auth-server
several times afterward, but there's no way for the oauth server to know
(without some events service).

**Comment by ckarlof** [comment]
@seanmonstar, ah I understand. The common use case here is that when Marketplace wants to use this functionality, they would have just asked the front end to require the user to enter her password (via `action=force_auth` in `GET /authorization`, so `fxa-lastAuthAt` value will be seconds ago.

**Comment by rfk** [comment]
My understanding is that the upstream force-auth flow (https://github.com/mozilla/fxa-content-server/issues/1957) will generate a fresh token, so checking the lastAuthAt as of token creation time is sufficient, and having this timestamp be specific to a particular token is the correct and desired behaviour.

**Comment by rfk** [comment]
I put this into code over in #205 so that we've got something concrete to discuss.
