### ISSUE TITLE
Verify BrowserID assertions locally

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#184]
There are some wins to verifying the BiD assertion locally:

* reduced latency for those requests
* increased reliability (TokenServer in Sync was seeing some 500s from the verifier occasionally, I believe)
* easier local dev (currently you have to run a hacked version of the verifier that allows http)

**Comment by rfk** [comment]
We should consider this for improving our load handling for upcoming readinglist deployment

**Comment by seanmonstar** [comment]
@ckolos would it be possible to point at the local IP of the verification server, so as to not need to do HTTPS and DNS and lightspeed, or no?

**Comment by ckolos** [comment]
@seanmonstar if you mean pointing the oauth process running on localhost:9010 at bv running at (say) localhost:9020, then sure. I would think that would be preferable actually...

**Comment by seanmonstar** [comment]
@ckolos Here's what I meant:

We have oauth.accounts.firefox.com, and verifier.accounts.firefox.com. OAuth needs to talk to verifier when verifying assertions. This MAY be the public URL (You might know better, it's a [variable in the template](https://github.com/mozilla-services/puppet-config/blob/master/fxa/modules/fxa_oauth/templates/default_config.json.erb#L4)). If it is, would it be possible to change it such that the URL points at the LOCAL IP of the verifier? Some sort of 10.0.0.54 or whatever?

If it's not possible, or if it's already that way, would it be best to just run another instance of verifier on the oauth boxes as you said (port 90whatever).

**Comment by ckolos** [comment]
Latency across ec2 networking caused issues with tokenservers flow when the verifier wasn't local. It's a good assumption that the same thing will be an issue for oauth. We'll want run it locally on a different port; that's how tokenserver is setup now.

**Comment by ckarlof** [comment]
Thanks @ckolos. I think we should move on this soon. I've concerned it's going to bite us on the ass once we start getting some traffic on the OAuth server.

A related concern is if we're going to see RL server -> OAuth server latency issues (for verifying OAuth tokens) and if we do, what we're going to do about it.

**Comment by mostlygeek** [comment]
A local verifier is a much better approach. 

- smooths out unpredictable errors
- removes the additional TLS overhead (CPU + ~250ms to 400ms latency)
- no additional bandwidth charges

**Comment by seanmonstar** [comment]
Cool! So, how do we get it done? Is it just a config piece, since we already have a way to build and run a browserid-verifier process elsewhere?

**Comment by ckolos** [comment]
@seanmonstar, most of the work is on our side; as long as the ap is already configured to point at "a" verifier, we should only need to modify which modifier it's looking at as well as add the required bits to the puppet configs.

**Comment by ckolos** [comment]
The changes required for this have been tested on a stage stack and merged to master. Should go live in train-36

**Comment by rfk** [comment]
thanks @ckolos, closing
