### ISSUE TITLE
Use JWTs as OAuth tokens

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#185]
This would make them directly verifiable by service providers and would not require a backend request to the OAuth verifier. We still have to deal with the revocation problem, which might require moving to a refresh token model.

**Comment by rfk** [comment]
Let's pick this up again once the refresh token work lands.  The idea (as Chris hinted above) would be to have refresh tokens stored in much the same way as current tokens, i.e. randomly-generated ids that map back to a database record and hence can be managed and revoked.

When you use one of these to get a short-lived access token, that access token can be a signed JWT that's easy for service providers to verify locally without calling back to our server.

**Comment by rfk** [comment]
This can come back as an Aha feature card when we decide to pick it up
