### ISSUE TITLE
Service discovery endpoint needed for easy lookup of OAuth related servers

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#187]
Also filed as https://github.com/mozilla/fxa-relier-client/issues/14

Part of mozilla/fxa-relier-client#13.

The relier client needs a mechanism to discover the origin of the content server without hard coding the value inside the client. The OAuth API contract is the OAuth server domain name is stable, other servers make no such promises. A hard coded value inside the client makes it very difficult to change the domain name of the servers without causing reliers some amount of pain.

A `/v1/config` endpoint or something would provide a list of URLs a relier (or library) should interact with. The URL list will include the content and profile servers at a minimum, and possibly others.

Background: The content server's origin is needed in the lightbox flow for the relier to be able to postMessage to the content server.

**Comment by shane-tomlinson** [comment]
@rfk - will do, though it will take a few days - I have a lot of holiday backlog to get through. :D

**Comment by shane-tomlinson** [comment]
@rfk - a `/config` route already exists, this could be used to send the additional required information.

**Comment by shane-tomlinson** [comment]
In fact, the only additional information needed is the `profileUri`

**Comment by shane-tomlinson** [comment]
A service discovery mechanism should report:

oauthUrl: oauth server URL with version suffix.
profileUrl: profile server URL with version suffix.
contentUrl: content server URL, no suffix necessary.

The goal for adding the version suffix is to be able to say "discover all the relevant URLs with the most recent version, from the oauth server"

Currently, `/config` reports the contentUrl with a `/oauth/` suffix.  I'm not sure where `/config` is called from, is the `/oauth` suffix necessary? Both oauthUrl and profileUrl would need to be added.

Perhaps this functionality would be better as a `/discovery` endpoint or something more focused?

**Comment by shane-tomlinson** [comment]
Link to #102

**Comment by shane-tomlinson** [comment]
@rfk, @seanmonstar, @ckarlof, @vladikoff, @zaach - concrete proposal for service discovery.

A `/config` endpoint already exists for service discovery but contains insufficient information for my use case.

### Some random thoughts
* OAuth reliers need to talk to one or more OAuth services: the oauth, content, and profile servers at a minimum.
* Every relier keeping a list of servers it needs to talk to is a drag, especially if they test against one stack and then release to another. (stable->prod for instance).
* The notion of versioning is used by the API of each OAuth service.
* The versions of each OAuth service can be changed independently.
* Reliers are most likely going to interface with the most recent version of an OAuth service and stay there until they have a reason to update.
* Reliers know which version of the OAuth service's protocol they speak.

### Desired solution attributes
* An OAuth relier should be able to discover an OAuth service's API URL. The URL should correspond to the version of the protocol the relier speaks.

### Proposal 1
Return a list of all versions of all known services. In this example, I change the format of the URLs, this is just for example purposes.

`GET /config` =>
```json
{
  "content": {
    "v1": "https://accounts.firefox.com"
  },
  "oauth": {
    "v1": "https://oauth.accounts.firefox.com/v1",
    "v2": "https://v2.oauth.accounts.firefox.com/",
    "v3": "https://v3.oauth.accounts.firefox.com/"
  },
  "auth": {
    "v1": "https://api.accounts.firefox.com/v1"
  },
  "profile": {
    "v1": "https://profile.accounts.firefox.com/v1",
    "v2": "https://profile.accounts.firefox.com/v2"
  }
}
```

#### Advantages
* The list can be pre-generated, little strain on the server.
* All endpoints can easily be discovered.

#### Disadvantages
* The list could grow very large as more services and versions are added.

### Proposal 2
The relier requests a specific list of services/versions:

`GET /config?content=v1&oauth=v2&profile=v2` =>
```json
{
  "content": "https://accounts.firefox.com",
  "oauth": "https://v2.oauth.accounts.firefox.com/",
  "profile": "https://profile.accounts.firefox.com/v2"
}
```

With this one, I could also see specifying the "latest" version of each:
`GET /config?content=latest&oauth=latest&profile=latest` =>
```json
{
  "content": "https://accounts.firefox.com",
  "oauth": "https://v3.oauth.accounts.firefox.com/",
  "profile": "https://profile.accounts.firefox.com/v2"
}
```


#### Advantages
* the returned list is very small/focused.

#### Disadvantages
* More strain on the server to create the JSON blob.

I'm somewhat partial to the 2nd.

**Comment by ckarlof** [comment]
Here's my thoughts from 6 months ago: https://github.com/mozilla/fxa-auth-server/wiki/Service-discovery-API

**Comment by ckarlof** [comment]
And previous discussion: https://github.com/mozilla/fxa-auth-server/issues/738

**Comment by rfk** [comment]
> GET /config

I kinda feel like we should version this, e.g. `GET /v1/config`.  Not sure how possible that is if it's an existing endpoint tho...

I suggest a variant of Proposal 1, purely in the interests of getting this done.  If we want to move towards something in the vein of Proposal 2, we could do it in a Proposal-1-compatible way by emitting the same format object, but only including the keys that the relier explicitly asked for.

@shane-tomlinson what do you think of the "com.firefox.sync.v15.tokenserver" namespacing convention from Chris's suggestion?

**Comment by ncalexan** [comment]
This has had more recent and meaty discussion, so I'll use it.  @Balakrishnan-Vivek is probably interested as well.

Fennec wants:
* auth
* token
* content
* oauth
* profile
* Reading List and other services
We might eventually want:
* device management endpoint (if it's not just auth)

**Comment by rfk** [comment]
mostly a note to myself: we should keep on eye on compatibility and future potential merger with the OpenID Connect discovery spec: http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

**Comment by rfk** [comment]
Migrating further discussion and prioritiazation to https://mozilla.aha.io/features/FXA-65
