### ISSUE TITLE
travis reports vulnerable module

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#192]
From https://travis-ci.org/mozilla/fxa-oauth-server/jobs/46316503

>> Name Installed Patched Vulnerable Dependency
>> inert 1.1.0 >=1.1.1 fxa-oauth-server > hapi

**Comment by shane-tomlinson** [comment]
A fix to this requires an upgrade to hapi 8.x. 7.5.3 still has the offending module.

**Comment by vladikoff** [comment]
Fixed via https://github.com/mozilla/fxa-oauth-server/commit/13c2d57bf75022680ab5b3bc22f989a0163bf080
