### ISSUE TITLE
Fail fast on invalid `action` parameters to GET /v1/authorization

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#194]
From @rfk in https://github.com/mozilla/fxa-oauth-server/pull/191/files#r22686284:

> Should we consider erroring out if an invalid action is specified? I can imagine people accidentally typoing this as e.g. force_signin.

I agree.

**Comment by rishibaldawa** [comment]
This file https://github.com/mozilla/fxa-oauth-server/blob/07efe68605c78b31c3babffeeb398530c9bb66cf/lib/routes/redirect.js#L18 ?

**Comment by rfk** [comment]
Yep, that's the one!

**Comment by rishibaldawa** [comment]
What if no action is provided? There's a test for this that'll fail if we just throw a invalidRedirect https://github.com/mozilla/fxa-oauth-server/blob/master/test/api.js#L224

Do we need to fix the test or continue the behavior ?

**Comment by seanmonstar** [comment]
The test is correct. No action should mean the default.
