### ISSUE TITLE
GET /v1/authorization needs to allow iframing

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#195]
GET /v1/authorization needs to allow iframing to support the iframe flow.

Background info: I incorrectly coded up the fxa-relier-client to skip the OAuth server to start the OAuth transaction. Instead, a user would go directly from the RP to the content server. https://github.com/mozilla/fxa-relier-client/pull/21 fixes this.

**Comment by shane-tomlinson** [comment]
Blocks mozilla/fxa-relier-client#21

**Comment by shane-tomlinson** [comment]
nm, the x-frame-headers are not set, I have something else going on. Closing as invalid.

**Comment by rfk** [comment]
>  the x-frame-headers are not set

We should consider setting them explicitly, if only to document that frameability is a requirement. from this level down.
