### ISSUE TITLE
Add "owners" to OAuth Clients

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#196]
Hey @rfk, @seanmonstar, I'm planning a PR to add "owners" to OAuth Clients.

******
![image](https://cloud.githubusercontent.com/assets/128755/5752381/ea67e93c-9c41-11e4-8e47-480f6e0a8017.png)
>  Figure 1: Creating a new client, adding an extra owner to that client

******

This will probably involve creating the following:
* a new table `client-owners`. such as 
```
 *   clientDevelopers: {
 *     <id>: {
 *       clientId: <client_id>,
 *       userId: <user_id>
 *     }
 *   }
```
* a new endpoint to add additional client owners ( i.e `/client-owners`) (Should this take UID as a parameter or something else?)
* changes to `/clients` API, such as only those with owner permissions can modify the client.

Am I forgetting anything or are there any issues with this approach? I appreciate your input and suggestions for this feature!  :book:

**Comment by vladikoff** [comment]
Some notes: 
* Clients should have an owner
* Being able to grant permission to manage clients that I created
* Need a way to list owners in the OAuth Console
* Existing clients will need their owners added manually
* We will need a way to get email from uid, and uid from email.
* `/client-owners` should take `email` instead of `uid`

**Comment by vladikoff** [comment]
![image](https://cloud.githubusercontent.com/assets/128755/5771499/60ed60ee-9d0c-11e4-89f7-30fd54ab4331.png)
> Figure 2: Updated diagram, feature split into 2 phases 

Phase 2 will require a way of getting an FxA `email` from a `uid`.

**Comment by seanmonstar** [comment]
Overall looks great. I don't understand why an there is a need to exchange a `uid` for an email, though.

**Comment by vladikoff** [comment]
>  I don't understand why an there is a need to exchange a uid for an email, though.

To list owners of a particular client in the console. If "client-owners" stores UIDs then we need to retrieve emails for those UIDs

**Comment by seanmonstar** [comment]
Ah, we actually keep the email that was used when a token is issued, to help the profile server out: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/schema.sql#L31

**Comment by vladikoff** [comment]
@seanmonstar the issue with emails is that those may be changed in the future, while the UID stays the same.

**Comment by seanmonstar** [comment]
This is true. Though, the best that can be done is perhaps to query the tokens for a uid, order by created_at, descending. This will get you the most recent email used.

The profile server, when asked for an email for a token, it just asks the OAuth server for the email, and is returned the email in that db column.

The real fix eventually would require receiving events from the fxa-auth-server when the user has changed their email.

**Comment by ckarlof** [comment]
Since the `uid` for `email` thing is to support multiple owners, I think we can punt on it for now.

**Comment by vladikoff** [comment]
Meeting Notes:
- Another way to set this up is to assign owners based on existing users in the console

**Comment by vladikoff** [comment]
@seanmonstar hey Sean, where did you want to store / keep track of the oauth console users? Should it be at the console level or the oauth server?

**Comment by seanmonstar** [comment]
@vladikoff that should live in oauth server, so that the same rules apply for anyone using the cli.

**Comment by rfk** [comment]
@vladikoff has all the useful stuff from this bug landed already with your developers work, or do we need to keep it open to track further follow-ups?

**Comment by vladikoff** [comment]
Oh forgot to close this. We have a Part 2 bug tracking already. Thanks!
