### ISSUE TITLE
CORS error on local installation - concept?

### ISSUE THREAD

**Issue by FinMike** [mozilla/fxa-oauth-server#213]
So fxa-auth-server is running on port 9000, fxa-oauth-server on 9010. 
Both are proxied by different apache virtual hosts (auth: accounts.domain.local, oauth: api-accounts.domain.local) for a reason: accounts.domain.local proxies several URL starting with /v1, api-accounts.domain.local is needed for /v1/authorization. Both can not be  proxied by the same vhost because of the recursive urls. Right so far?

Problem: cross-origin-request blocked for same origin rule at api-accounts.domain.local/v1/authorization when performing login procedure. 

I'd be really glad for any hint on how to configure a single proxy vhost under these circumstances. Maybe such a hint would be fine in the docs for oauth-server as well. Sorry for bothering you.

**Comment by vladikoff** [comment]
Here is a sample nginx proxy config that passes CORS https://github.com/mozilla/fxa-dev/blob/b9b6f347c786428b347b82d38fb67e2c2fd1b827/roles/auth/templates/nginx.conf.j2

**Comment by FinMike** [comment]
thanks, vladikoff, but those in your example are two locations which are not nested. Here, we have to send requests for /v1* to port 9000 and for /v1/authorization to 9010.

**Comment by rfk** [comment]
> Both can not be proxied by the same vhost because of the recursive urls. Right so far?

I don't really understand what you mean here or precisely what's causing the problem.  Can you please go into a little more detail about the config, what request is triggering the CORS error and what the precise error is?

**Comment by FinMike** [comment]
Hi @rfk, 

I do have to put the request for /v1/authorization through proxy to fxa-oauth on port 9010, and the other request for urls beginning with /v1 to fxa-auth at port 9000, don't I?

ok, so here we go - the relevant parts of the output of console while trying to login:
(sorry, errors in german - and a bit messy, as I haven't figured out how to format them here)
I suppose the first and last lines are most important here. 

-----8<----------------
Diese Website hat eine ungültige Strict-Transport-Security-Kopfzeile angegeben.
Unbekannte Eigenschaft 'speak'. Deklaration ignoriert.
	

speak: none;

	

GET https://accounts.domain.local/scripts/templates/partial/close-button.mustache
	
200 OK
		422ms	
text.js (Zeile 303)
GET https://accounts.domain.local/scripts/templates/sign_in.mustache
	
200 OK
		415ms	
text.js (Zeile 303)
GET https://accounts.domain.local/scripts/templates/legal.mustache
	
200 OK
		440ms	
text.js (Zeile 303)
GET https://accounts.domain.local/scripts/templates/sign_up.mustache
	
200 OK
		407ms	
text.js (Zeile 303)
GET https://accounts.domain.local/scripts/templates/confirm.mustache
	
200 OK
		427ms	
text.js (Zeile 303)
GET https://accounts.domain.local/scripts/templates/force_auth.mustache
	
200 OK
		439ms	

**... ok up to:**

GET https://accounts.domain.local/config
	
200 OK
		24ms	
jquery.js (Zeile 9631)
GET https://accounts.domain.local/i18n/client.json
	
200 OK
		19ms	
jquery.js (Zeile 9631)
POST https://api-accounts.domain.local/v1/certificate/sign
	
200 OK
		37ms	
fxa-client.js (Zeile 1614)
Passwort-Felder sind auf einer unsicheren (http://) Seite vorhanden. Dies ist ein Sicherheitsrisiko, durch das Zugangsdaten gestohlen werden können.
	

POST https://oauth-accounts.domain.local/v1/authorization
	
500 Internal Server Error
		16ms	
"NetworkError: 500 Internal Server Error - https://oauth-accounts.domain.local/v1/authorization"
authorization
Cross-Origin-Anfrage blockiert: Die Same-Origin-Regel verbietet, die externe Ressource auf https://ffoau.domain.local/v1/authorization zu lesen. Dies kann gelöst werden, indem die Ressource auf die gleiche Domain geschoben wird oder CORS aktiviert wird.
Unauthorized

**Comment by rfk** [comment]
> I do have to put the request for /v1/authorization through proxy to fxa-oauth on port 9010, and the 
> other request for urls beginning with /v1 to fxa-auth at port 9000, don't I?

Well, that request has to end up at the fxa-oauth-server, yes.  But it's not the only one, there are several API endpoints on the oauth server:

  https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#api-endpoints

> I'd love to move that ressource to the same domain (api-accounts.domain.localhost), but then I'm
> back to the start of this issue. 

You could host the fxa-auth-server API under a sub-path.  For example, in our dev environment we have fxa-content-server at https://stable.dev.lcip.org and fxa-auth-server at https://stable.dev.lcip.org/auth

The fxa-oauth-server *should* be sending CORS headers by default.  Can you confirm whether any CORS headers are being sent?  (For example, `curl -v -X OPTIONS https://oauth-accounts.domain.local/v1/authorization` from the command-line)

**Comment by FinMike** [comment]
Sorry I hat to confess myself with other things not worth knowing in the meantime.

> You could host the fxa-auth-server API under a sub-path. 

now that was indeed helpful. Basic, but very helpful. Consider this solved. 
as for the second question: 

    # curl -v -X OPTIONS http://127.0.0.1:9010/v1/authorization
    * About to connect() to 127.0.0.1 port 9010 (#0)
    *   Trying 127.0.0.1... connected
    * Connected to 127.0.0.1 (127.0.0.1) port 9010 (#0)
    > OPTIONS /v1/authorization HTTP/1.1
    > User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
    > Host: 127.0.0.1:9010
    > Accept: */*
    > 
    < HTTP/1.1 200 OK
    < content-type: application/json; charset=utf-8
    < content-length: 2
    < access-control-allow-origin: *
    < access-control-max-age: 86400
    < access-control-allow-methods: GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS
    < access-control-allow-headers: Authorization, Content-Type, If-None-Match
    < access-control-expose-headers: WWW-Authenticate, Server-Authorization
    < strict-transport-security: max-age=15552000; includeSubdomains
    < cache-control: no-cache
    < Date: Thu, 12 Feb 2015 18:42:27 GMT
    < Connection: keep-alive
    < 
    * Connection #0 to host 127.0.0.1 left intact
    * Closing connection #0

Looks ok for me, don't it?
Again, thanks for your time and efforts!

**Comment by rfk** [comment]
> Looks ok for me, don't it? 

Yep, those headers are as expected.
