### ISSUE TITLE
GitCop tweaks?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#219]
I noticed we have some automated policing of our commit policy:

  https://github.com/mozilla/fxa-oauth-server/pull/218#issuecomment-74019147

This is pretty sweet!  I spend more time than I ought trying to sanity-check my commit messages for the guidelines here so it'll be nice to have someone watching over me :-)

@seanmonstar I guess this is something you hooked up?

Is there much potential for tweaking the wording to make it a little more welcoming for potential first-time contributors?  I'm thinking along the lines of opening with "Thanks for contributing!  I'm an automated checker and I noticed the following...".

**Comment by pdehaan** [comment]
Looking at https://gitcop.com/features it seems like we may be able to set a custom header/footer (although not sure if thats available on free tier).

Bonus points if we can use an animated GIF in the footer. I think @jrgm was proposing something like:
![](http://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Emergency_Light.gif/120px-Emergency_Light.gif)

**Comment by pdehaan** [comment]
I vote for something more whimsical in the footer, like this:
![](https://31.media.tumblr.com/fa6a31e326066bb27776066150c8c810/tumblr_inline_njkqu4wXlW1r79k32.gif)
**Figure 1:** @ckarlof disapproves of your PR!

**Comment by seanmonstar** [comment]
It's setup using gitcop.com. There's only a single line for the header, and it didn't mention anything about markup. (I could probably shove markdown in there, just to see...)

For now, I adjusted the message to:

> Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

**Comment by rfk** [comment]
Works for me, thanks @seanmonstar
