### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by FinMike** [mozilla/fxa-oauth-server#220]
So this is what I get from the fxa-oauth logfile while trying to log into the fxa- servers on my intranet now. As always, even RTFM pointers are greatly appreciated. 

    fxa-oauth-server.db.VERBOSE: proxied {"method":"getClient","ret":{"name":"synclocal","redirectUri":"https://sync.domain.local/1.0/sync/1.5","imageUri":"https://content.domain.local/images/firefox.png","canGrant":true,"id":[154,142,235,127,210,225,204,79],"hashedSecret":"aa0e408b092eb8271944cc733c554d70159c490d085b3182c1af6628b9734c12","whitelisted":true,"createdAt":"2015-02-13T14:04:53.777Z","secret":"aa0e408b092eb8271944cc733c554d70159c490d085b3182c1af6628b9734c12"}}
    fxa-oauth-server.assertion.ERROR: verify.error Error: DEPTH_ZERO_SELF_SIGNED_CERT
        at SecurePair.<anonymous> (tls.js:1380:32)
        at SecurePair.emit (events.js:92:17)
        at SecurePair.maybeInitFinished (tls.js:979:10)
        at CleartextStream.read [as _read] (tls.js:471:13)
        at CleartextStream.Readable.read (_stream_readable.js:340:10)
        at EncryptedStream.write [as _write] (tls.js:368:25)
        at doWrite (_stream_writable.js:225:10)
        at writeOrBuffer (_stream_writable.js:215:5)
        at EncryptedStream.Writable.write (_stream_writable.js:182:11)
        at write (_stream_readable.js:601:24)
    fxa-oauth-server.summary.ERROR: summary {"code":500,"errno":999,"method":"post","path":"/v1/authorization","agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0","t":41,"client_id":"9a8eeb7fd2e1cc4f","auth":null,"payload":["client_id","scope","assertion","response_type","redirect_uri"],"stack":"Error: DEPTH_ZERO_SELF_SIGNED_CERT\n    at SecurePair.<anonymous> (tls.js:1380:32)\n    at SecurePair.emit (events.js:92:17)\n    at SecurePair.maybeInitFinished (tls.js:979:10)\n    at CleartextStream.read [as _read] (tls.js:471:13)\n    at CleartextStream.Readable.read (_stream_readable.js:340:10)\n    at EncryptedStream.write [as _write] (tls.js:368:25)\n    at doWrite (_stream_writable.js:225:10)\n    at writeOrBuffer (_stream_writable.js:215:5)\n    at EncryptedStream.Writable.write (_stream_writable.js:182:11)\n    at write (_stream_readable.js:601:24)"}

Well, the certificate I'm using for the proxy is self-signed, ok, but there is no ssl involved between proxy and the oauth server, or is there?
 
Setup is the following:
 - awsbox

    {
      "contentUrl": "https://content.domain.local",
      "db": {
        "driver": "memory"
      },
      "clients": [
        {
          "name": "synclocal",
          "redirectUri": "http://sync.domain.local/token/1.0/sync/1.5",
          "imageUri": "https://content.domain.local/images/firefox.png",
          "canGrant": true,
          "id": "9a8eeb7fd2e1cc4f",
          "hashedSecret": "aa0e408b092eb8271944cc733c554d70159c490d085b3182c1af6628b9734
          "whitelisted": true
       }
     ],
     "env": "prod",
      "logging": {
        "level": "verbose"
      }
   }

- dev.json:

    {
      "browserid": {
        "issuer": "127.0.0.1:9000",
        "verificationUrl": "https://sync.domain.local/token/1.0/sync/1.5"
      },
      "contentUrl": "https://content.domain.local/oauth/",
      "clients": [
        {
          "name": "synclocal",
          "redirectUri": "https://sync.domain.local/token/1.0/sync/1.5",
          "imageUri": "https://content.domain.local/images/firefox.png",
          "canGrant": true,
          "id": "9a8eeb7fd2e1cc4f",
          "hashedSecret": "aa0e408b092eb8271944cc733c554d70159c490d085b3182c1af6628b9734c12",
          "whitelisted": true
        }
      ],
      "localRedirects": true,
      "logging": {
        "level": "ALL",
        "fmt": "pretty"
      }
    }

 - apache vhost setup

    VirtualHost *:443
        ServerName   accounts.domain.local:443
        UseCanonicalName Off
        SSLEngine on
        SSLProtocol all -SSLv3
        SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM
        SSLCertificateKeyFile /etc/ssl/httpd/apache.key
        SSLCertificateFile /etc/ssl/httpd/apache.crt
        ProxyRequests   off
        ProxyPass               /oauth  http://127.0.0.1:9010 
        ProxyPassReverse        /oauth  http://127.0.0.1:9010
        ProxyPass               /auth   http://127.0.0.1:9000/auth 
        ProxyPassReverse        /auth   http://127.0.0.1:9000/auth 
        ProxyPass               /.well-known    http://127.0.0.1:9000/.well-known
        ProxyPassReverse        /.well-known    http://127.0.0.1:9000/.well-known
   /VirtualHost

**Comment by seanmonstar** [comment]
That error is happening in nodejs' `tls` module.

A Google search yield this [possible answer](http://stackoverflow.com/a/23715832/101059):

> The second problem is the one that really causes that DEPTH_ZERO_SELF_SIGNED_CERT error. You are giving all your certificates - CA, server, and client - the same Distinguished Name. When the server extracts the issuer information from the client certificate, it sees that the issuer DN is the same as the client certificate DN and concludes that the client certificate is self-signed.
>
> Try regenerating your certificates, giving each one a unique Common Name (to make the DN also unique). For example, name your CA certificate "Foo CA", your server certificate the name of your host ("localhost" in this case), and your client something else (e.g. "Foo Client 1").

**Comment by FinMike** [comment]
Hi, thanks for caring. 
> Try regenerating your certificates, giving each one a unique Common Name (to make the DN also > unique). For example, name your CA certificate "Foo CA", your server certificate the name of your > host ("localhost" in this case), and your client something else (e.g. "Foo Client 1").

did that, if I got you right. accounts.domain.local, sync.domain.local and content.domain.local  have their own cert, even with a self-signed CA. (as this is for a local intranet, I don't expect to buy an official cert once a year). Now tls says "verify.error Error: SELF_SIGNED_CERT_IN_CHAIN". I suppose that's not what you meant. 

> You are giving all your certificates - CA, server, and client - the same Distinguished Name.

However, accounts.domain.local proxies fxa-auth and fxa-oauth now (see #213). Could this be part of the problem?

**Comment by rfk** [comment]
@FinMike sorry for the delay in following up on this, we're all doing a bit of a (tradtional) scramble to ensure our Q1 deliverables are on track.  Are you still having problems with your setup?

Looking at the request that fails, I see `"method":"post","path":"/v1/authorization"` so I guess this is happening when the oauth-server tries to verify the assertion submitted by the client.  To do this, it must fetch the `/.well-known/browserid` document hosted on the `publicUrl` of the auth-server.  Which is probably where it's making a call out via tls, since I assume that the public-facing URL of the auth-server is https.

You may be able to directly add the certificates directly to your local trusted root store; I've no idea of the specifics of  doing that though.

**Comment by rfk** [comment]
I'm not sure there's any concrete action we can take within FxA to help with this issue, so I'm going to close it out.

**Comment by FinMike** [comment]
@rfk thank you ever so much for being helpful again, and sorry for the delay on my side now. 
Meanwhile, I have found the solution: npm needs to know the full set of certs itself to work. Your idea, Ryan:
> You may be able to directly add the certificates directly to your local trusted root store; I've no idea > of the specifics of doing that though.
 
1. generate a self-signed root ca cert, a key and a cert and include these in the config of your proxy http server. 
2. for the user running npm, include these cert files in the .npmrc, parameters are   
* ca="whateveryounameCA.crt"
* key="whateveryounameit.key"
* cert="whateveryounameyourcert.crt"
each filename including the full path.

**Comment by FinMike** [comment]
After finally being able to cram a self-signed CA cert into node settings by 
   npm config set ca < cat CA-certfile.pem
wheras CA-certfile.pem has to contain quotation marks at the beginning and the end of it
I think that problem is solved for me. Remember, this is for intranet and testing purposes only, never try that on a live server which is online on the 'net. 
Just wrote that up here for anyone trying to google a solution. 
However, big thank you all for caring.
