### ISSUE TITLE
Update all clients to have a value for redirect_uri

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#230]
Mostly canGrant clients have blank uris, we should set that to some value.

-  ~~create a bugzilla bug for other clients~~
- [x] update fxa-dev
- [x] update oauth-server configs
- [x] gui console must require redirect_uri when adding a new client (bug https://github.com/mozilla/fxa-oauth-console/issues/33)
- [x] /client endpoint should also validate for blank redirect_uri

via a meeting with @ckarlof

**Comment by rfk** [comment]
Some non-url constant string token that indicates "no redirect_uri, this is an implicit grant client?"

**Comment by vladikoff** [comment]
`urn:ietf:wg:oauth:2.0:no_redirect`? 
`urn:ietf:wg:oauth:2.0:oob` ("out of band" callback) ?
`urn:ietf:wg:oauth:2.0:oob:auto` ?
`urn:ietf:wg:oauth:2.0:grant`? 

>  that indicates "no redirect_uri, this is an implicit grant client"?

I'm not sure if it should indicate "implicit grant" or should just indicate that it is a non-redirect flow or a non-web flow.

**Comment by ckarlof** [comment]
We have a precedent of using urn: URIs for non-Webby type redirects (in WebChannel for Hello), so I think one is appropriate here as well.

Bike shed away.

**Comment by vladikoff** [comment]
Will double check, @jrgm mentioned that redirect uris were added.

**Comment by vladikoff** [comment]
Cleaned this up a bit, left a bug open for the oauth console https://github.com/mozilla/fxa-oauth-console/issues/33
