### ISSUE TITLE
oauth-console needs access to the client management port

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#232]
the latest oauth console now returns a 404 when requesting for clients, I assume due to the new client management port: 

![](https://cloud.githubusercontent.com/assets/128755/6577679/0004d684-c716-11e4-87ba-fc8e71494813.png)

What should we do about this for dev environments?

ping @rfk @seanmonstar 

Ref: https://github.com/mozilla/fxa-oauth-console/issues/23

**Comment by seanmonstar** [comment]
This should be fixed with https://github.com/mozilla/fxa-dev/pull/123
