### ISSUE TITLE
'npm start' does not start the internal server

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#233]
Seems like only the main server is started

**Comment by jrgm** [comment]
So, does this need to happen? For the most part, typical use of oauth doesn't need the internal api. It works now on fxa-dev boxes. Can this be closed.

**Comment by vladikoff** [comment]
Eh, I feel like `npm start` should start it because it is the *development mode*. For instance, nodemon restarts the server(s) after you make changes to files. 

It might be confusing for future development / contributions if not all components start together. 
@seanmonstar thoughts on this? feel free to close if you think this is not necessary.

**Comment by seanmonstar** [comment]
I'm +0. I'm sure you desire it more, since it's needed when you work on the console locally...

Though, as you point out, `npm start` is for development. I'd merge a PR!

**Comment by vladikoff** [comment]
from mtg: @seanmonstar kill it
