### ISSUE TITLE
Invalid assertions should produce a 401, not a 400

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#234]
From IRC:
```

15:43 nalexander: rfkelly: why would I get a 400/109 from fxa-oauth-server when I submit a bogus assertion?
15:43 nalexander: rfkelly: how can that not be a 401?
15:43 rfkelly looks
15:43 nalexander: rfkelly: https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md
15:44 nalexander: rfkelly: that is, the server API is making it hard for clients to distinguish "configuration is bad (client id, etc)" from "my state is bad" (401).
15:44 rfkelly: how is the assertion bogus?
15:44 nalexander: rfkelly: 'cuz I generated it locally with certificate "BAD CERTIFICATE"
15:45 nalexander: rfkelly: I'm trying to test a particular oauth 401 flow.  And I expected to get a 401 from the oauth server when I came with a bad cert.
15:45 rfkelly: so, possibly it's bailing out while trying to parse the assertion, rather than when trying to verify it, hence unexpected error
15:45 rfkelly: I agree it should be a 401
15:45 nalexander: rfkelly: because how do I distinguish bogus cert from expired cert?  They should both look like 401, since I'm unauthed.
15:45 nalexander: rfkelly: I have a single day deadline for this RL oauth work, so I'm goign to pretend 400 is 401 for nwo.
15:46 rfkelly: ok
15:46 nalexander: rfkelly: but if it made it to a bug, I'd appreciate it :)
15:46 rfkelly: that can probably happen ;-)
15:49 rfkelly: nalexander: if there's formatting errors in the assertion, it could catch it here and trigger the 400 rather than 401:
15:49 rfkelly: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/authorization.js#L89
```

We should dig into this and make sure that we're helping clients distinguish well-formed-but-invalid-assertion from you-sent-us-garbage.

**Comment by rfk** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1148094

@seanmonstar if this turns out to be a relatively simple fix, it would be great to prioritise and maybe even get it into train-34 is possible.  Anything we can do to reduce roadbumps for readinglist client development will be valuable.

**Comment by seanmonstar** [comment]
So, the first error is a legit `400`, since the it's hitting the parameter format validation before even verifying anything actually inside the assertion.

The latter can be easily fixed.

**Comment by rishibaldawa** [comment]
is this the line to fix? https://github.com/mozilla/fxa-oauth-server/blob/master/lib/error.js#L115

**Comment by rfk** [comment]
@rishibaldawa yes, I think so, along the the corresponding invalid-assertion test in ./tests/api.js

**Comment by jrgm** [comment]
Um, is https://github.com/mozilla/fxa-oauth-server/issues/234#issuecomment-86791241 saying that 400 was correct and shouldn't be changed. What is the test case that should be failing right now?

**Comment by rfk** [comment]
IIRC @seanmonstar was saying that a malformed assertion should produce a `400`, while a well-formed assertion that fails verification should give a `401`.  Currently they both produce a `400`.

**Comment by rishibaldawa** [comment]
Just to add to that, I think the test case was setup incorrectly as well and is part of the PR.
