### ISSUE TITLE
How to get the service status?

### ISSUE THREAD

**Issue by Natim** [mozilla/fxa-oauth-server#238]
Hello,

We are using Firefox Oauth Server from the readinglist and we would like to add its status in our readinglist ``__heartbeat__`` endpoint.

Basically this endpoint return a 200 if the service works and a 503 if one of the service it needs is not available (database, cache, etc.)

In the case of a service provider like the readinglist not being able to validate an Oauth token is a case of failure for our server. We could probably verify that the oauth server is working.

Do you have a ``__heartbeat__`` endpoint that we could use?

**Comment by seanmonstar** [comment]
@Natim There is a `/__heartbeat__` route on the oauth server.

**Comment by pdehaan** [comment]
@seanmonstar It's at https://oauth.accounts.firefox.com/__heartbeat__, correct?
Should it return an "OK" or something, or returning statusCode === 200 means that everything is working and anything else is a fail?

**Comment by vladikoff** [comment]
> @seanmonstar It's at https://oauth.accounts.firefox.com/__heartbeat__, correct?
Should it return an "OK" or something, or returning statusCode === 200 means that everything is working and anything else is a fail?

it does a db ping and if that fails the status code will not be 200. hopefully the status code should be enough

**Comment by seanmonstar** [comment]
Status codes only. 200 all is well, 500 the world is ending.

**Comment by pdehaan** [comment]
Fantastic, thanks gents!
![](http://gifsb.in/hat-tip/5ajbeWB.gif)

**Comment by pdehaan** [comment]
@Natim, if you need it, the stage endpoint would be https://oauth.stage.mozaws.net/__heartbeat__ :beers:
