### ISSUE TITLE
OAuth Devs Part 2: Adding a developer to an existing client

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#239]
Once https://github.com/mozilla/fxa-oauth-server/pull/222 lands we will need another patch that will allow us to add more than one owner to an oauth client. 

The oauth console in this case will have a special view where the client creator can add other developers to that client. 
Mock up:
![image](https://cloud.githubusercontent.com/assets/128755/7054732/778cb6b0-de0c-11e4-9679-ce01e1f6da8c.png)

**Comment by rfk** [comment]
@vladikoff I think we should de-prioritise further work on this console unless we have people asking for it.  Moving this out of "in progress" but feel free to add it back if you think we should keep it.

**Comment by vladikoff** [comment]
We can make it part of this milestone: https://mozilla.aha.io/features/FXA-63 AKA FxA Developer Portal

Closing for now until we get to it, we can reopen if needed.
