### ISSUE TITLE
Restrict scopes for untrusted reliers

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-oauth-server#243]
We may want to restrict scopes for certain reliers, e.g. a third party relier that can only request the `profile` scope.

Related #143.

**Comment by rfk** [comment]
Thanks @zaach.  s/may/definitely/, at least in the short-term while we figure out a more nuanced story.

**Comment by zaach** [comment]
One question: should we silently strip ungranted scopes or return an error? Stripping seems nicer for the user and worse for the dev, while returning an error seems the inverse.

**Comment by rfk** [comment]
I think erroring out will be more useful that this early stage.

**Comment by rfk** [comment]
Also related: #188

**Comment by rfk** [comment]
In conversation with @seanmonstar he pointed out that we actually have a bunch of more granular profile-related scopes, e.g. `profile:email`, `profile:avatar`, and I assume soon `profile:displayName` or similar.  If we allow blanket `profile` scope then third-party reliers will be able to access all of these pieces of information, as well as any new profile-related data that we begin to store at a later time.

Perhaps we should restrict this to just the scopes that we know will be need in the short term, e.g. `profile:email` and `profile:uid` but not `profile:avatar`.  @zaach, thoughts on how much of the profile data we actually want to expose?

**Comment by rfk** [comment]
It looks like they may be hoping to include the avatar picture as well, based on the black circle staring back at me on the auth completion screen:
![pocket_welcome_page](https://cloud.githubusercontent.com/assets/34695/7312326/4da9b4d8-ea8c-11e4-96fb-d386013b6258.png)

**Comment by rfk** [comment]
s/certain reliers/untrusted reliers/ since we don't want to have to handle this on a case-by-case basis.

**Comment by zaach** [comment]
@rfk Aha. Perhaps we have a hardcoded (or configurable) set of scopes that are available for non-whitelisted clients?

**Comment by seanmonstar** [comment]
Ideally, this permission choosing would come from a permission screen in the content-server, and the oauth server wouldn't need to police it. However, until then, we would basically only allow `profile:email`, `profile:uid`, and `profile:avatar`, I suppose.

**Comment by zaach** [comment]
If we're feeling generous we can throw `profile:display_name` in there as well.

**Comment by rfk** [comment]
> Perhaps we have a hardcoded (or configurable) set of scopes that are available

Right, that's more-or-less what I was thinking as a (necessary but ugly) first step.

**Comment by rfk** [comment]
Note that we need this to go live simultaneously with https://github.com/mozilla/fxa-profile-server/issues/108
