### ISSUE TITLE
Find a way to share the memory db between internal.js and server.js

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#247]
Sort of related to https://github.com/mozilla/fxa-oauth-server/issues/233
When using both internal and main servers the memory database is separate. OAuth clients and OAuth developers are out of sync.

**Comment by seanmonstar** [comment]
I guess a way would be that the script run for `npm start` could require both bin scripts and `start` them, or be a separate script that starts both servers. That way, both servers would be running in the same process locally.

**Comment by vladikoff** [comment]
from mtg: @seanmonstar says kill it
