### ISSUE TITLE
Add extra client meta-data for third-party reliers

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#249]
Tracking bug to add additional client meta-data in service of https://github.com/mozilla/fxa-content-server/issues/2347 and https://github.com/mozilla/fxa-content-server/issues/2346.  We'll need at least ToS/PP links for each relier.  @zaach can you think of any other fields we will need?

**Comment by rfk** [comment]
(In case it wasn't obvious, this is going to involve a db migration)

**Comment by zaach** [comment]
Those fields should be fine. We're keeping the "should we redirect after verification" option as a query parameter on the content server for now.
