### ISSUE TITLE
Return empty string for clients with no imageUri

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#250]
I just spotted the following while watching network requests:
```
GET https://oauth-stable.dev.lcip.org/v1/client/749818d3f2e7857f
{
  "id": "749818d3f2e7857f",
  "name": "Pocket web dev",
  "image_uri": "https://"
  "redirect_uri": "https://firefoxauth.dev.readitlater.com/ff_auth"
}
```

We should just return `""` rather than `"https://"` for reliers without an imageUri.

**Comment by vladikoff** [comment]
This was an issue with the console and required parameters. Fixed via https://github.com/mozilla/fxa-oauth-console/issues/24. Will be deployed to oauth-stable soon.

**Comment by seanmonstar** [comment]
Yep, the oauth server doesn't do addition to that field. What's coming out is what was put in (sounds like it was a bug in the console).
