### ISSUE TITLE
Refactor hard-coded db name in sql query

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#252]
I noticed that one of our queries hard-codes the db name `fxa_oauth`:

  https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/mysql/index.js#L132

Since this is a configuration option, we should refactor the query to either not require an explicit db reference, or to pull it from config.

**Comment by seanmonstar** [comment]
Hrm, looking at the query, is there any need to have it in there at all? Seems it could just be deleted...

**Comment by vladikoff** [comment]
Fixed via https://github.com/mozilla/fxa-oauth-server/commit/792d262b0f3e046a458af63b7d298bf224ec44ec
