### ISSUE TITLE
[meta] drop the whitelisted column in clients table and associated code and config

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#267]
this will affect fxa-dev, stage and prod dbs, fxa-oauth-console, others.

**Comment by rfk** [comment]
IIUC fxa-oauth-console is fixed, I just filed PRs to fxa-dev and fxa-oauth-client to complete the change...@jrgm what else needs to happen before we can just drop the column and all support for it?

**Comment by rfk** [comment]
Need to re-open due to #301
