### ISSUE TITLE
Cannot create whitelisted clients in console

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-oauth-server#270]
Reported by Kit via email:

> Looks like it’s not possible to set it as a whitelisted client on https://oauth-stable.dev.lcip.org/console…when I check the “whitelisted client” box and click “Update,” I get a 400 in the network inspector.

/cc @vladikoff

**Comment by vladikoff** [comment]
Related to https://github.com/mozilla/fxa-oauth-server/commit/83e145b0a25d164d612f89968d00ce428d0c7aac

Will patch this soon...

**Comment by vladikoff** [comment]
fixed in v0.3.8 of the console, deploying right now...
