### ISSUE TITLE
Document commit-message format in CONTRIBUTING.md

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#272]

**Comment by rfk** [comment]
Let's put this in the top-level fxa repo, and link to it from CONTRIBUTING.md

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-oauth-server/commit/a00167ce0b141cd09f8377ecc981073e8e9146f4
