### ISSUE TITLE
Allow "ttl" property for implicit token grants

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#292]
When using the implicit flow to create an access token, it should be possible to pass "ttl" paramter to customize the expiry time of the token.

ref https://bugzilla.mozilla.org/show_bug.cgi?id=1181959

**Comment by rfk** [comment]
@philbooth here's a nice high-value-but-well-scoped backend bug; we need this API to take a `ttl` param when using `response_type=token`:

  https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#post-v1authorization

**Comment by philbooth** [comment]
Sorry @rfk, I missed this in my emails yesterday. Making a start now. :)
