### ISSUE TITLE
Unusual number of long-running 401 requests on the auth server

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#293]
Here's a fairly representataive sample of some 401s from our production nginx logs:

![screen shot 2015-07-09 at 16 57 47](https://cloud.githubusercontent.com/assets/34695/8589632/b487f902-265b-11e5-90de-b98efbec9c60.png)

Two things are odd about this:

* I would not expect clients to ever post an invalid assertion to the /authorization endpoint, so there may be a client bug happening here
* Many of these requests take multiple seconds to complete, which really shouldn't be necessary

**Comment by rfk** [comment]
Unfortunately @seanmonstar is out for the next week and unable to dig into this; @jrgm any suggestion of where we should start digging to find more details here?

**Comment by rfk** [comment]
Looking at the *successful* `POST /v1/authorization` requests shows then completing uniformly in a few tens of milliseconds.

**Comment by seanmonstar** [comment]
There should be some new logs timing the verification of the assertion and
the db check that the client is allowed implicit grants.

**Comment by rfk** [comment]
Cool.  I don't believe the app logs are currently making their way into kibana, although I'd be delighted to be wrong about that.  @jrgm any chance you can get at the application logs corresponding to these requests?

**Comment by jrgm** [comment]
So the app logs have always been in kibana afaik. [This custom graph](https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#dashboard/temp/AU5554yV3q0_6xoph7aU) shows 2 things. 1) the number of 401 increased markedly around 07/03, and 2) the UA is overwhelmingly Fx42 (so Nightly) on Windowses.

As for the 8 second times, I'm looking further.

**Comment by jrgm** [comment]
Oh yeah, I remember now. Exactly 8 seconds is https://github.com/mozilla/browserid-verifier/blob/master/lib/config.js#L27-L31, which intentionally 2 seconds less than the limit on the squid proxy IIRC.

**Comment by jrgm** [comment]
So I do see a number of requests in the squid proxy for api-accounts.f.c/.well-known/browserid that take > 1000ms to complete (with a few hitting the 8000ms limit and aborting squid). But I don't see the equivalent sort of latency in actual requests hitting the auth-server for /.well-known/browserid. Not sure what the bottleneck is.

**Comment by mhammond** [comment]
I don't have access to the custom graph - what is the raw count of 401s before and after 3rd of July? I'm wondering if it is possible it's from a single user (ie, me ;)?

**Comment by jrgm** [comment]
The graph looks like this. Sorry didn't capture the scale but the peak is ~70:

<img width="632" alt="oauth-401-uptick" src="https://cloud.githubusercontent.com/assets/758162/8631860/c6d56996-2737-11e5-86fe-e527bcbe64f6.png">

**Comment by mhammond** [comment]
Profile images in the hamburger menu landed on July 3rd. This means that profile images have started being requested as the browser starts (whereas before it was on Sync prefs only, and that only loaded when sync prefs were shown). I've also identified that the browser attempts to fetch the profile multiple times concurrently (which has a patch yet to land). I've also identified what I *think* is a race condition in generating the assertions used to get the oauth token to fetch the profile.

In general, these 401s would *not* have been noticed by the user as at least one of the concurrent requests worked. The only evidence would have been in logs that generally aren't shown by default.

So all in all, I think this points to a few distinct client bugs :(

**Comment by mhammond** [comment]
FTR, bug https://bugzilla.mozilla.org/show_bug.cgi?id=1182740

**Comment by rfk** [comment]
@jrgm what should our next steps be here?  Do we need to add some more monitoring on either side of this dance to catch one of this timeout spikes in the act?

**Comment by rfk** [comment]
FWIW, I'm no longer seeing the originally-reported behaviour.  There are still a few spikes of high-latency 401s, but they're not in the majority.  It's possible they're being swamped by 401s from accounts.firefox.com.cn traffic, but anyways...closing this out since there are no obvious follow-up tasks remaining.
