### ISSUE TITLE
Use human-readable duration values in config

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#296]
As a follow-up to #294, we should use convict's human-readable duration values like "2 weeks" rather than the current "1000 * 60 * 60 * 24 * 7 * 2" stuff we have going on right now.

**Comment by pdehaan** [comment]
Warning: https://github.com/mozilla/node-convict/issues/68
We've been bit by this a few times. So last I checked Convict w/ durations works great when defining in the convict file as defaults, but has a bug (I think) if you try and define that duration in an external JSON file which you're loading as a config.
