### ISSUE TITLE
Commit 155d2ce (to drop `whitelisted` and rename `secret` to `hashedSecret`) cannot go to production

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#301]
re: https://github.com/mozilla/fxa-oauth-server/pull/284 and https://github.com/mozilla/fxa-oauth-server/commit/155d2ce39967513382e38948c9490a327d4441e8

I cannot do:
```
ALTER TABLE clients CHANGE secret hashedSecret BINARY(32);
ALTER TABLE clients DROP COLUMN whitelisted;
```
to prepare the database for oauth train-42. Either one will cause an immediate production outage.

Database changes must always be compatible with train-N (production) and train-(N+1) (the next one). 

Column renames can never be done. Dropping a column can only happen AFTER the current production stable release no longer refers at all to the column that will be dropped.

I have two pull requests coming up to fix this for train-42:

1. Revert commit `155d2ce`, but keeping the patches change and adding to that changes to reverse the two ALTER statements. (This is to avoid breaking `latest` and other, and having to manually fix things). 

2. A follow-on PR to (1) which puts back in the changes to remove all references to `whitelisted`, which is the second step in obsoleting this column (the third step is actually dropping the column AFTER that has gone live in production).

/cc @ckolos

**Comment by rfk** [comment]
ugh, sorry @jrgm, my bad - I should have caught this in review
