### ISSUE TITLE
Check that account deletions are being properly processed in production

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#310]
We definitely have some code for this, but I'm not sure if we got it all the way through to production.  @seanmonstar please check it out.

**Comment by rfk** [comment]
@seanmonstar I recall we landed a patch to enforce some of this, is there any work remaining to do on this bug?

**Comment by seanmonstar** [comment]
Technically, I don't think the config is set up yet, but I don't know what the values would be. However, the merged patched will not allow a deployment (to prod or stage) without that config being filled in.
