### ISSUE TITLE
Update Travis to not use sudo

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-oauth-server#313]
Saw this warning while looking at a Travis log:

> This job ran on our legacy infrastructure. Please read [our docs on how to upgrade](http://docs.travis-ci.com/user/migrating-from-legacy/).

So if we want to jump onto the newer/better/faster/stronger Travis infastructure, we'd need to add this to our [.travis.yml](https://github.com/mozilla/fxa-oauth-server/blob/master/.travis.yml) file: `sudo: false`

..but, we're currently using `sudo` to `sudo apt-get install libgmp3-dev`.

We may be able to work around this by copying this from the [**mozilla/fxa-content-server** ./travis.yml](https://github.com/mozilla/fxa-content-server/blob/master/.travis.yml) file:

```
addons:
  apt_packages:
    - libgmp-dev
```

Not sure if we want to also run this repo against Node 0.12 while we're at it, or we can save that for a separate bug.

**Comment by vladikoff** [comment]
FixeD!

**Comment by pdehaan** [comment]
thanks @dannycoates!
