### ISSUE TITLE
Provide a procedure for changing client secrets without service outage

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#317]
If we ever need to change the client_secret associated with an oauth client, IIUC there's currently no way to do that without them taking a small service outage.  We have to simultaneously update the secret in the config on our servers and the config on our clients.

We should consider formalizing a pattern for rotating these secrets without a service outage, e.g. by having both a "current secret" and "previous secret" to allow the following sequence:

* generate the new secret on our side, make it the current secret and bump the old secret to "previous"
* send the new secret to the client and wait for them to change over to
* remove the old secret entirely

**Comment by vladikoff** [comment]
@seanmonstar to mentor?

**Comment by seanmonstar** [comment]
@vbudhram All "clients", which are things like the Firefox browser, or addons.mozilla.org, receive a `client_id` and `client_secret`. These are used as part of the OAuth flow to trade a code for an OAuth bearer token.

Currently, if that secret is leaked, the process for updating the stored secret would be updating the row in our mysql database, and simultaneously giving the new secret to the affected client. Any requests for oauth tokens from the client before they have the new secret deployed would be forbidden.

This bug is to add the possibility of 2 keys being valid for a client, while the client upgrades and removes the older key.

**Comment by seanmonstar** [comment]
Some pieces that would need to be done:

- Add support for a second key in the database https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/mysql/schema.sql#L12
- Mirror the new database api for the memory database (which is used for local-dev and tests) https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/memory.js#L22
- The `/token` route, which receives the `client_id` and `client_secret`, would need to be aware of the database possibly having 2 tokens for a given client, and proceeding if the secret matches either of them. https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/token.js#L175-L195
- Tests for these things

I believe we can allow for ops to insert the new key, and delete the old key, manually when an instance occurs. I think it's a non-goal to figure out how to do that automatically.

**Comment by vbudhram** [comment]
Thanks @seanmonstar! I think I have a better idea of what needs to be done now.

**Comment by vbudhram** [comment]
> generate the new secret on our side, make it the current secret and bump the old secret to "previous"

@rfk @seanmonstar What are some possible avenues for doing the client secret rotation? Could we potentially have a new endpoint that issues the new secret?

**Comment by rfk** [comment]
Note that currently, production secrets are all provisioned manually; moving to a more automated process is a good longer-term goal but probably out of scope for this bug.  IIRC they're all read from the config file and synced to the db on app server startup, so the procedure for rotating production secrets would probably be to add them in the config file.

For completeness, it probably makes sense to add or extend something in the "clients" API [1] that allows a client to rotate its own secret.  I'm not sure exactly what that would look like.

[1] https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#get-v1clientid

**Comment by seanmonstar** [comment]
> I believe we can allow for ops to insert the new key, and delete the old key, manually when an instance occurs. I think it's a non-goal to figure out how to do that automatically.

I'd say let that be part of a different issue, if we need it eventually.

**Comment by vbudhram** [comment]
Sounds good to me!
