### ISSUE TITLE
need to ignore token expiry in train-42 too

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#319]
This change https://github.com/mozilla/fxa-oauth-server/commit/b14c38177dee513483893befe93233c174cd0b1c is not in v0.42.0. 

@seanmonstar - can you take care of getting that in place and tagging v0.42.1?

**Comment by seanmonstar** [comment]
https://github.com/mozilla/fxa-oauth-server/compare/v0.42.0...v0.42.1
