### ISSUE TITLE
Mock outstanding error logs in test suite

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-oauth-server#334]
It's currently noisy running the tests, as when we test some error conditions of the database, the errors are shot out to console. Since these errors are expected, it'd be better to mock them out, so the test suite doesn't look like something horrible happened.

**Comment by shane-tomlinson** [comment]
@seanmonstar, I don't have a good feel for the priority of this, I am putting this into the backlog, change it if you want a bump.

**Comment by shane-tomlinson** [comment]
@seanmonstar - are we going to do this? If not, should we close it out?

**Comment by pluto5004** [comment]
Hi... Shall I take this as part of Outreachy contribution

**Comment by vladikoff** [comment]
@pluto5004 yes please!

**Comment by deeptibaghel** [comment]
@vladikoff yeah, happy to work this :)
