### ISSUE TITLE
Update mozlog dependency to 2.0.2 or greater?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#337]
It's got a few cleanups and improved error handling.  Our use of caret-range `mozlog: "^2.0.0"` might mean we get this for free, but npm-shrinkwrap might undo that.  Not sure, so I'm recording it in a bug for completeness.

**Comment by seanmonstar** [comment]
it would require `npm update mozlog` and then `npm shrinkwrap`.
