### ISSUE TITLE
Remove awsbox

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-oauth-server#348]
We don't use it anymore. There's `.awsbox.json`, `scripts/aws*`, and the devDependency.

**Comment by vladikoff** [comment]
@jrgm do we still use awsbox stuff? last time we tried to remove it from the content server I was told that we still need it for something

**Comment by jrgm** [comment]
@vladikoff - I'm not aware of any direct uses of awsbox in fxa-* repos. I do use awsbox to standup 123done boxes in stage, but I've been meaning to replace that with a Cloudformation stack + ansible. 

However, there are some mentions of awsbox in https://github.com/mozilla/fxa-dev/search?utf8=%E2%9C%93&q=awsbox for the fxa-dev boxes. If there are any key-value pairs unique to awsbox.json that are still needed, they should be move to another config file in those lists.

**Comment by vladikoff** [comment]
Fixed!
