### ISSUE TITLE
Add explicit config option for inserting client db recrods at startup

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#363]
/cc @jrgm, I found a reference to this tucked away in my todo stack so I'm filing the bug.

We currently provide the ability to auto-insert oauth client records into the db at startup, but it's disabled on `isProdLike` environments.  Unfortunately our fxa-dev environments are "prod like" and they'd really benefit from this functionality.  Let's replace the `isProdLike` check with something more specific, like a config option for whether or not to initialize the db on startup.

**Comment by jrgm** [comment]
Yeah, I have a branch with this change, and was just trying it on a fxa-dev build.
