### ISSUE TITLE
Purge expired access tokens from the db

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#366]
Once an access token is expired, there's no point it leaving it hanging around in the db taking up space.  We should set up a background pruning job to get rid of them.

Depends on #365, for obvious reasons.

**Comment by rfk** [comment]
IIUC this is no longer blocked in #365; instead it's the preferred method for getting the work in #365 out to production.  We need to purge the nominally-expired-but-not-yet-invalidated oauth tokens from the production db in small batches, until we reduce them to a sufficiently low volume that we can roll out #365 without a thundering-herd problem.

**Comment by rfk** [comment]
/cc @vbudhram since we talked about this earlier today.

As you can see from https://github.com/mozilla/fxa-oauth-server/issues/365 and its several linked PRs, our access tokens are supposed to expire after a brief period and ideally should be deleted from the database.  Unfortunately we have a large backlog of tokens that are very old but still technically active, and if we just expire them all at once, it causes a thundering herd of clients trying to generate new tokens and swamps the server with load.

So we need to take a look at purging expired tokens from the database, both for good housekeeping, and to clear the backlog of old active tokens so that we can properly enable expiry in production.

**Comment by rfk** [comment]
Potential wrinkles that will make this less than straightforward:

* There are so many old tokens that trying to delete them all in a single query would likely grind the db to a halt; we'll have to do some sort of batching to catch up on tokens that should ideally have been deleted some time ago.
* One of our reliers, Pocket, wants to convert their access_tokens into refresh_tokens, but we haven't coordinated a way to do this yet.  We probably need to leave Pocket's oauth tokens in the db even if they're expired, until we can figure out the details there.

**Comment by vbudhram** [comment]
Reopening, pending running scripts in https://github.com/mozilla/fxa-oauth-server/pull/401 to cleanup tokens.

**Comment by rfk** [comment]
@jrgm and @jbuck, putting this on your radar for train-65 - the oauth-server now contains a script that can be run to purge expired oauth tokens.  We should be able to use it to gradually expire the huge backlog of outstanding oauth tokens, and then set it up as a periodic background job to keep the number of outstanding tokens under control.

**Comment by vladikoff** [comment]
from mtg: "We need to run the script!"

**Comment by vladikoff** [comment]
cc @rfk @jrgm

**Comment by vladikoff** [comment]
This seems to be working, reopen if need changes to scripts or dev work. 👍
