### ISSUE TITLE
flaky test on travis reporting duplicate database info

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#376]
For example, see https://api.travis-ci.org/jobs/101651867/log.txt?deansi=true

      2) should not insert already existing clients
fxa-oauth-server.db.mysql.ERROR: updateDbSchema Error: ER_DUP_FIELDNAME: Duplicate column name 'authAt'
    at Query.Sequence._packetToError (/home/travis/build/mozilla/fxa-oauth-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)

Doesn't always happen. Not sure what's up with it.

**Comment by vladikoff** [comment]
Filed https://github.com/travis-ci/travis-ci/issues/5452

**Comment by jrgm** [comment]
This could use more attention. It's a common failure running test on travis these days, which is a time sink. e.g., recent https://travis-ci.org/mozilla/fxa-oauth-server/builds/108349970

**Comment by rfk** [comment]
The most recent link provided doesn't the `ER_DUP_FIELDNAME`, but I can repro a similar flaky failure locally by just running the tests in a loop:

```
while DB=mysql npm test; do true; done;
```

Digging in a bit now...

**Comment by rfk** [comment]
I think the tests are actually terminating themselves during the db patcher run.  If I comment out this line:

https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/mysql/index.js#L113

Then they seem to pass consistently.  We're supposedly stubbing it out for the tests here:

https://github.com/mozilla/fxa-oauth-server/blob/master/test/db/mysql.js#L76

But maybe that's not working consistently for some reason.
