### ISSUE TITLE
Intelligently choose default action for /v1/authorization

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#379]
For the FxA/AMO integration, the user flow would be greatly helped if we can direct the user to either `/signup` or `/signin` based on whether they have an existing account.

The content-server currently has logic to do this based on browser state, e.g. you get `/signin` by default if you've previously used FxA on that computer.  But can we do something more reliable on the backend?

Proposal: when visiting `/v1/authorization` with `email=foo@bar.com` but no `action=` param, we check whether `foo@bar.com` has an existing account and choose either `action=signin` or `action=signup` as appropriate.

This is a bit of an abstraction violation, as we'll likely need to talk to the auth-server to determine whether the account exists.  But frankly I consider the merging of auth and oauth dbs inevitable so I'm not too upset about it...

@seanmonstar thoughts?

**Comment by seanmonstar** [comment]
Hm, it's possible the user already has localStorage in their browser, and it'd be faster to check that first, right?

**Comment by rfk** [comment]
IIUC, this would mean the content-server does all the checking:

* Look in localStorage for existing account info on the local machine
* If there's nothing there, ask the auth-server whether an account exists for that email

This saves time in the first case, but adds a round trip in the second, which I'm not sure would be a worthwhile tradeoff.

**Comment by seanmonstar** [comment]
The round trip would also exist in the oauth-server (until it has direct read access to the auth db), so it wouldn't be much slower. I suppose slower in that the oauth-server can make a in-network request, skipping ssl, whereas the browser cannot.

**Comment by rfk** [comment]
> the oauth-server can make a in-network request, skipping ssl

Even if not skipping ssl or anything, they're in the same datacenter so it's going to be faster.

I don't have a strong preference here, but it occurs to me that we don't really have a public API for checking "is this email already registered?".  We have several APIs from which you can *infer* this, e.g. you could call `/v1/password/change/start` with a bad passphrase and catch the `errno=102` response.  But that's yuck.

ISTM that having the content-server do this check means committing to a more public API for checking email status, which may make people uncomfortable.  But Google seems to do something similar via https://accounts.google.com/accountLoginInfoXhr, to which you can post an email and determine whether the account exists.

@seanmonstar what do you think is a better approach on balance?

**Comment by seanmonstar** [comment]
Interesting point. It seems either way, we would end up with an endpoint that could easily tell anyone if an email is registered: if done in the oauth server, then any `GET /v1/authorization?email=foo` request could check the `Location` header to see which action was appended by the oauth server.

**Comment by rfk** [comment]
Indeed.  I think we're already committed to allowing that information link in the interests of better UX.

**Comment by rfk** [comment]
IIUC we're going to close this in favour of doing it in fxa-content-server
