### ISSUE TITLE
Wrong method returns 404 rather than 405

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/fxa-oauth-server#383]
The verify endpoint here:

https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#post-v1verify

expects a POST call, however issuing a GET results in an HTTP 404 NOT FOUND response, rather than a HTTP 405 METHOD NOT ALLOWED response, which I think is the correct response in this situation.  If the URL is well formed it should not return a 404?

**Comment by vladikoff** [comment]
Huh sorry, first time I hear about this pattern. Does this mean if I have a `POST /verify` endpoint then I should also set 405s for all possible HTTP Method definitions? Or is `GET` special?

**Comment by rfk** [comment]
For total spec compliance with HTTP, a 405 is "more correct" than a 404.  But I don't think we should have to specify all the other methods explicitly, rather, this should be taken care of by the web framework.  There may be an issue for this in Hapi (which may have been wontfixed, I don't know).

**Comment by vladikoff** [comment]
Ref: https://github.com/hapijs/hapi/issues/1534

**Comment by vladikoff** [comment]
WONTFIX in hapi, let me know if we want to change it for our case :+1:

**Comment by jaredkerim** [comment]
It's not worth implementing outside of the framework, it's unfortunate that the core maintainer doesn't think it's worth implementing as part of the routing or request handler.
