### ISSUE TITLE
restrict redirect_uri to `https://` and `urn:`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#388]
This extends from [this comment in the content server](https://github.com/mozilla/fxa-content-server/pull/3469#discussion_r52017618). @vladikoff mentioned the OAuth server allows any arbitrary string as the redirect_uri in the call to `/authorization`, which is exceptionally lenient. @rfk and I talked today about tightening this up to only allow `https://` and `urn:` URIs, and additional protocols can be added if required.

I imagine both the `redirect_uri` passed to `/authorization` and the `redirect_uri` registered for each client would both need to be validated.

Ref https://github.com/mozilla/fxa-content-server/pull/3469, #387

**Comment by rfk** [comment]
> tightening this up to only allow https:// and urn: URIs

`http://` URLs are probably required for localhost; I don't think any of our production reliers should be using insecure http.
