### ISSUE TITLE
Use fresh "kid" when generating fresh keys

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#393]
Our gen_keys.js script currently uses a static `kid: "2015.12.16-1"` for all keys that it generates.  In the interests of good key-management hygiene, we should generate a fresh key id for each new key.  Options include using a hash of the key data, or a timestamp.

No big deal, just something I noticed.

**Comment by vladikoff** [comment]
@rfk @seanmonstar for Tuesday triage

**Comment by vladikoff** [comment]
from mtg: cc @rfk @seanmonstar what do we need to do here?
