### ISSUE TITLE
why do we have this condition on routing?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#396]
https://github.com/mozilla/fxa-oauth-server/blob/master/lib/server/index.js#L29-L35

**Comment by rfk** [comment]
I don't know...I assume that one of the routes was failing validation for not-easy-to-fix reasons, but it would be nice if we'd left a comment for our future selves :-)

**Comment by rfk** [comment]
Looks like it was added a long time ago in https://github.com/mozilla/fxa-oauth-server/pull/111/files#diff-c945a46d13b34fcaff544d966cffcabaR27

**Comment by seanmonstar** [comment]
This is useful for testing/dev, but it results in 500s. A case this
occurred was when the validation would check for a redirect_uri (on getting
client info), but can_grant clients had an empty string. This triggered
Hapi to blow up the request with a 500, when I feel it shouldn't have.

**Comment by rfk** [comment]
I don't feel strongly enough about this either way to suggest a change, so let's leave the status quo alone
