### ISSUE TITLE
Why is scripts/gen_keys saving pubkey for old and privkey for new

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#397]
https://github.com/mozilla/fxa-oauth-server/blob/master/scripts/gen_keys.js#L38-L48

Is that a typo?

**Comment by vladikoff** [comment]
from meeting: major confusion

**Comment by seanmonstar** [comment]
The main key is needed to sign OIDC assertions, and for clients to verify
those with the public key.

The old key is only useful for assertions that were signed in the past.
Clients still need to verify them, so only the public part of the key is
necessary.

There are rules at the bottom of lib/config.js to make sure there aren't
mistakes.
