### ISSUE TITLE
add remoteAddressChain to app logs

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#415]
Probably applies to profile-server too. Record the xff header.

**Comment by vladikoff** [comment]
@jrgm we should chat about this

**Comment by vladikoff** [comment]
from mtg:

* which requests? summary requests -  https://github.com/mozilla/fxa-oauth-server/blob/245ca8638ab5af51130984374a3bc0a50d68d7af/lib/server/index.js

* here it is in auth server: https://github.com/mozilla/fxa-auth-server/blob/master/lib/log.js#L147
