### ISSUE TITLE
return granted scopes used in client-tokens list

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#431]
We should show the user the scopes that were used when they logged in into some relier.
We should also show those somehow in the Devices and Apps list.

**Comment by vladikoff** [comment]
@rfk , @ryanfeeley says we should not do this and not say anything in the apps list,  because "the account has no sensitive info".

thoughts?

**Comment by rfk** [comment]
I can see @ryanfeeley's point short-term.  Right now the only useful things we could say in the apps list are "Can read your profile info" and "Can modify your profile info", which doesn't really help the user that much.

Perhaps we should just revisit this if and when we add additional scopes with extra powers?

**Comment by rfk** [comment]
(Although if it's a small change, it's probably still worth returning the scopes in the API, even if we don't display them in the UI yet).
