### ISSUE TITLE
Invalidate refresh tokens on client-token DELETE

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#432]
When disconnecting client also delete the refresh tokens and other stuff...

**Comment by rfk** [comment]
@vladikoff I'm going to flag this into the "lockbox beta" milestone, since IIUC lockbox will be issuing itself refresh tokens.

**Comment by linuxwolf** [comment]
Invalidating the refresh token when invalidating an access token needs more consideration.  There are legitimate reasons to delete an access token but **not** the refresh token.

A more traditional web app would ship the current access token up to the browser-side content scripts, and keep the refresh token to do things when the user isn't active in the web content.  In this case, I could see revoking the access token when the app server detects a loss of a user's interactive session (thereby minimizing any damage that token getting around could do), but keep the refresh token to do long-term things for the user.  This behavior would seem to prevent that.

**Comment by rfk** [comment]
I agree that we should not do this in every case.  The bug description doesn't make it obvious, but "client-token DELETE" is actually referring to a specific HTTP API call, used internally by FxA when users go into "devices and apps" in the FxA settings page and revoke an OAuth app.  Revoking the refresh token is definitely the right thing in that particular case :-)

(The only reason it doesn't already do that, is that no other reliers have been issuing themselves refresh tokens)
