### ISSUE TITLE
Tests pass locally, fail in Circle and Travis

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-oauth-server#443]
```
  51 passing (14s)
  1 failing

  1) /v1 "before all" hook:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by philbooth** [comment]
I got them to pass on the fourth attempt. Is this a feature?

**Comment by seanmonstar** [comment]
> Is this a feature?

Clearly.

[Here's that before all hook](https://github.com/mozilla/fxa-oauth-server/blob/master/test/api.js#L174-L190). Could be that the db ping is not working?

**Comment by jrgm** [comment]
I've seen this fail locally.

**Comment by shane-tomlinson** [comment]
@jrgm reports that he's seen this locally too.

**Comment by vbudhram** [comment]
Recently saw this error in Travis, not sure if related. Maybe some database timing issue.

```
fxa-oauth-server.db.mysql.ERROR: updateDbSchema Error: ER_DUP_FIELDNAME: Duplicate column name 'authAt'
```

**Comment by rfk** [comment]
I'm going to close this out as it hasn't seen movement in a while, let's open a fresh bug if we're still seeing test failures.
