### ISSUE TITLE
Implement PKCE to support public clients using the code grant flow

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#465]
@vladikoff I'm filing this to capture the task from our meeting with @Natim yesterday.  Per that discussion:

* The hoverpad webextension and mobile app must be considered "public clients".  This is OAuth spec terminology for "clients which can't keep anything confidential, and so can't meaningfully be authenticated with a client_secret".
* We want to support such clients using the code-based login flow, so that they can obtain encryption keys.
* Let's hew to existing standards and best practices for allowing such clients in a secure way.

In practice I think that means implementing the "Proof Key for Code Exchange" spec [1].  It's specified in excruciating detail in the RFC but the core idea is that:

* When initiating the OAuth dance, the client generates and remembers a random secret called the `code_verifier`. They provide `code_challenge = HASH(code_verifier)` as an additional input parameter to the flow, and we remember this value for later use.
* At the end of the dance, when the client has received the `code` parameter is wants to exchange it for a token, they must provide the original value of `code_verifier` along side it.
* On the server, we receive `code` and `code_verifier`, and check that `HASH(code_verifier)` matches the value of `code_challenge` that was submitted at the beginning of the flow.

The end result is that only the actual client that initiated the login flow is able to redeem the authorization code at the end, so we can protect public clients against other apps snooping their login flow.  For example, this will prevent other webextensions from snooping and using the returned authorization code.

IIUC the required changes from the oauth-server perspective will include:

* Adjust the db schema for client records, to be able to mark some of them as "public clients" that do not have a client_secret.
* At the start of the flow in `GET /authorization`, accept and remember the new `code_challenge` parameter.
* In the middle of the flow, in `POST /authorization` where we generated an authorization code, ensure that the code gets associated with the correct value of `code_challenge`. 
* At the end of the flow in `POST /token`:
    * accept the new `code_verifier` parameter
    * check that it matches the `code_challenge` associated with the incoming authorization code

[1] https://tools.ietf.org/html/rfc7636

**Comment by vladikoff** [comment]
This is a good article for this: https://www.authlete.com/documents/article/pkce/index

**Comment by seanmonstar** [comment]
> Adjust the db schema for client records, to be able to mark some of them as "public clients" that do not 
have a client_secret.

I believe this is in the DB already, though perhaps with a different name. The `canGrant` column was meant for clients that don't have a secret, but do the implicit auth grant flow, since they can mint a browserid assertion, which we trust instead of a secret.

**Comment by rfk** [comment]
> since they can mint a browserid assertion

I wonder if this is slightly different; we should not expect e.g. the Firefox Notes client to be able to mint an assertion.
