### ISSUE TITLE
Allow token refresh using the PKCE flow

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#472]
Need to handle the case here: https://github.com/mozilla/fxa-oauth-server/blob/52d935183b7bbd5813f52def13ac14c22acd162a/lib/routes/token.js#L177 where clients don't have a client_secret and want to renew their poor token 💻

**Comment by vladikoff** [comment]
cc @rfk

**Comment by rfk** [comment]
My read of the spec here is that we don't need PKCE in this flow - it doesn't transit any untrusted parties so there's nothing for PKCE to protect.  Rather, we should just remove the client_secret check for clients that don't have one.

From https://tools.ietf.org/html/rfc6749#section-6, when processing a refresh token request:

>   The authorization server MUST:
>
>  o  require client authentication for confidential clients or for any
>      client that was issued client credentials (or with other
>      authentication requirements),
>
>   o  authenticate the client if client authentication is included and
>      ensure that the refresh token was issued to the authenticated
>      client, and
>
>   o  validate the refresh token.

So the logic here should simply be:

* If the client has a client_secret, check that it's provided and valid in the refresh request
* If the client does not have client_secret, check that one was not provided in the refresh request

@vladikoff what do you think?
