### ISSUE TITLE
ClientId for Firefox iOS

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-oauth-server#473]
For https://github.com/mozilla/fxa-bugzilla-mirror/issues/335, I am reusing the content-server clientId to fetch the avatar. Should we generate and add a new clientId specifically for Firefox iOS? There does not appear to be an existing one in the [configs](https://github.com/mozilla/fxa-oauth-server/blob/master/config/dev.json#L7).

@seanmonstar Is this difficult to do?

**Comment by seanmonstar** [comment]
Yes, a specific client for iOS sounds like a good idea to me.

The config there is used for local dev, the oauth-console is needed to create clients in dev.lcip, and an ops bug to create it in stage/prod. We prefer to keep the `client_id` the same across all of them, for simplicity sake.

**Comment by vladikoff** [comment]
> the oauth-console is needed to create clients in dev.lcip

We also manage a client config in fxa-dev here: https://github.com/mozilla/fxa-dev/blob/3cf6901e51f1318575975f5eb21cd517d562f6c8/roles/oauth/templates/config.json.j2#L16

so you don't need to use the console in each dev environment to have that client.

**Comment by vbudhram** [comment]
iOS client has been added and tested in https://github.com/mozilla-mobile/firefox-ios/pull/3071, closing.
