### ISSUE TITLE
Correct issuer for FxiOS

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-oauth-server#479]
Not sure if this is the correct repo but from https://github.com/mozilla-mobile/firefox-ios/pull/3071#discussion_r135065552. The Sync client in iOS uses `127.0.0.1` and content-server uses it's public url.

@rfk @seanmonstar Thoughts or preference on which this should be?

**Comment by seanmonstar** [comment]
I don't really understand the issue. This is about the issuer of the certificate that the auth-server signs?

**Comment by vbudhram** [comment]
Sorry, this is about the issuer that iOS uses to make the assertion that is exchanged for Oauth token. I wasn't sure if there was a preference or a best practice for what this value should be.

**Comment by seanmonstar** [comment]
It needs to agree with the value the auth server uses when signing. If it doesn't, it will error: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/browserid.js#L77

**Comment by rfk** [comment]
> the issuer that iOS uses to make the assertion

The iOS client should not be adding an "issuer" field itself, that's set by fxa-auth-server.  If the client *does* add an "issuer" field into the part of the assertion that it controls, I would expect that value to be ignored by everything else in the system.

**Comment by rfk** [comment]
After poking around in the client code, it's my considered opinion that whatever value you put in here will just be ignored by every other part of the system: https://github.com/mozilla-mobile/firefox-ios/pull/3071#discussion_r136463975

**Comment by vbudhram** [comment]
Resolved by https://github.com/mozilla-mobile/firefox-ios/pull/3071#discussion_r136560533, closing.
