### ISSUE TITLE
PKCE implementation `code_verifier` does not match specifications

### ISSUE THREAD

**Issue by linuxwolf** [mozilla/fxa-oauth-server#495]
This implementation forces `code_verifier` to be exactly 32 (ASCII) characters long.  However, according to [RFC 7636 § 4.1](https://tools.ietf.org/html/rfc7636#section-4.1), the `code_verifier` is expected to be between 32 and 128 (ASCII) characters long.

**Comment by rfk** [comment]
Hrm, it also looks like we're accepting arbitrary strings, while the spec says it should only contain b64urlsafe characters "with a minimum length of 43 characters and a maximum length of 128 characters".

**Comment by linuxwolf** [comment]
Ignoring impacts to any existing clients, the fix is very straightforward: https://github.com/mozilla/fxa-oauth-server/compare/master...linuxwolf:pkce_code_verifier

The question, though, is what impact is acceptable to existing implementations?

**Comment by vladikoff** [comment]
> The question, though, is what impact is acceptable to existing implementations?

You mean if it breaks other PKCE users? It's just Firefox Notes and we can fix it up in the sync branch 👍

**Comment by linuxwolf** [comment]
The only other implementation (pending) I'm aware of is Lockbox.  As long as we've got a bit of fair warning when this makes it to the scoped-keys dev server, we should be fine, too.

**Comment by vladikoff** [comment]
@linuxwolf fix deployed to https://oauth-scoped-keys-oct10.dev.lcip.org/ server that has your lockbox prototype clients
