### ISSUE TITLE
/v1/token does not seem to support HTTP Basic authentication scheme

### ISSUE THREAD

**Issue by nhnt11** [mozilla/fxa-oauth-server#513]
I was using the client-oauth2 node library [1] to implement a client, and noticed failure in the token-obtaining step: "Err: Bad Request". This was because the library's getToken() API does not include client_id and client_secret in the request body if client_secret is available: it uses an Authorization header in the HTTP request.

I did some digging and the RFC seems to mandate that the server support this HTTP header for authentication [2].

On the other hand, it also specifies that the server may support including the parameters in the request body, but does not recommend it. Based on this I submitted a pull request [3] to client-oauth2 to support this with explicit opt-in by the caller.

I can try submitting a pull request to modify token.js around line 177 [4] if I find time later, but thought I'd open this issue in the meantime.

Please let me know if I'm missing something and/or if there's something I can read to learn more about this.

[1] https://github.com/mulesoft/js-client-oauth2
[2] https://tools.ietf.org/html/rfc6749#section-2.3.1
[3] https://github.com/mulesoft/js-client-oauth2/pull/66
[4] https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/token.js#L177

**Comment by juliemccracken** [comment]
@rfk , with Vlad on PTO, can you please take a look at this? It's a blocker.

**Comment by rfk** [comment]
Thanks @nhnt11, nice catch.  We're definitely off-spec here, I'll take a quick look...

**Comment by rfk** [comment]
The (hopefully!) fix for this should be in fxa train-104, which will work its way through our deployments over the next week or so.  You can track progress via this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1432698
