### ISSUE TITLE
Update development instance to latest version

### ISSUE THREAD

**Issue by nhnt11** [mozilla/fxa-oauth-server#523]
https://oauth-stable.dev.lcip.org/ is still on v1.103.0. We need the Authorization header patch for blurts, which is in v1.104.0.

**Comment by vladikoff** [comment]
cc @jrgm

**Comment by jrgm** [comment]
updated to v1.106-ish. Running functional tests and green so far.

[
  {
    "commit": "20863f876fccabcbc41b10a279b91b635d683735",
    "version": "1.106.3",
    "l10n": "9426c68ff1d7e124f7236ae56784b38a370f26b5",
    "tosPp": "6dd5592083e9fc8992d5bb1e30157ea653644b2a",
    "source": "unknown",
    "url": "https://stable.dev.lcip.org/__version__?env=stable"
  },
  {
    "version": "1.106.0",
    "commit": "597bfab79f5fe2773a86c1b0598c5f6f2cf038c2",
    "source": "https://github.com/mozilla/fxa-auth-server.git",
    "url": "https://stable.dev.lcip.org/auth/__version__?env=stable"
  },
  {
    "version": "1.106.0",
    "commit": "378360537c27ec0761d5bd2fbf9117e68b07844c",
    "source": "https://github.com/mozilla/fxa-oauth-server.git",
    "url": "https://oauth-stable.dev.lcip.org/__version__?env=stable"
  },
  {
    "version": "1.106.0",
    "commit": "9b3366652e678b5b50329f9b22b0f551b67490e8",
    "source": "https://github.com/mozilla/fxa-profile-server.git",
    "url": "https://stable.dev.lcip.org/profile/__version__?env=stable"
  }
]
