### ISSUE TITLE
automated changelog is borked

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-oauth-server#524]
https://github.com/mozilla/fxa-oauth-server/blob/master/CHANGELOG.md

v1.106.0 note is empty and stray `<a name"1.106.0">`, `<a name"1.105.0">`, `<a name"1.104.0">` fragments of literal text.

**Comment by vladikoff** [comment]
aw :(

**Comment by deeptibaghel** [comment]
@vladikoff sure i will work this :)
