### ISSUE TITLE
Support `action=email` to enable the email-first flow for OAuth reliers.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#539]
See https://github.com/mozilla/fxa-content-server/issues/6009

Changes should be limited to https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/redirect.js.

If `action=email`, the `action` query parameter must be propagated to the content server.

**Comment by vladikoff** [comment]
I am worried that from an OAuth server point of view the `action` param is way too generic.

**Comment by shane-tomlinson** [comment]
> I am worried that from an OAuth server point of view the action param is way too generic.

Can you expand?

**Comment by vladikoff** [comment]
@shane-tomlinson ah I see we already had in the codebase. It's ok then, I will just try to remember what `action` means and does more :P.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson ah I see we already had in the codebase. It's ok then, I will just try to remember what action means and does more :P.

I had a quick look at both the OpenID Connect and OAuth 2 spec and didn't find mention of an "action" query parameter anywhere, though section 3.1.2.1 of the OpenID Connect spec says that "Other parameters MAY be sent". IIRC we used `action` in the content server because the oauth server already made use of it.

I see that `action` is already part of our [publicly defined API](https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#get-v1authorization), though it's not mentioned [in the MDN docs](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/Introduction#OAuth_2.0_API).

**Comment by rfk** [comment]
> I had a quick look at both the OpenID Connect and OAuth 2 spec and didn't find mention
> of an action query parameter anywhere

Yep, I haven't seen any standard way of allowing the relier to choose the desired flow, so we have to go our own way here.  It'd be nice if we got to a point where relier didn't have to care about this, and email-first is probably a step in that direction.
