### ISSUE TITLE
Require contact info when provisioning OAuth credentials

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#557]
During the audit of outstanding OAuth relier credentials, it was very difficult to collectively remember which teams requested which creds. It seems this could be solved by requiring contact and or bugzilla bug info for each set of credentials so that the next time we do an audit, we know who to contact.

**Comment by rfk** [comment]
Huge +1 to this.  What does it look like in practice, another db field or two in the "clients" table to record this info?

**Comment by shane-tomlinson** [comment]
> Huge +1 to this. What does it look like in practice, another db field or two in the "clients" table to record this info?

I imagine so. Since the table is pretty small, adding a couple of new columns shouldn't cause too much headache.

**Comment by rfk** [comment]
Migrated to https://github.com/mozilla/fxa-auth-server/issues/2688
