### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-oauth-server#558]
> npm outdated
Package            Current  Wanted  Latest  Location
bluebird            2.11.0  2.11.0   3.5.1  fxa-oauth-server
buf                  0.1.0   0.1.0   0.1.1  fxa-oauth-server
commander           2.14.1  2.15.1  2.15.1  fxa-oauth-server
convict              4.0.2   4.0.2   4.2.0  fxa-oauth-server
eslint-plugin-fxa    1.0.0     git     git  fxa-oauth-server
fxa-shared           1.0.5   1.0.5   1.0.9  fxa-oauth-server
grunt-eslint        18.0.0  18.0.0  20.1.0  fxa-oauth-server
hapi                16.6.3  16.6.3  17.4.0  fxa-oauth-server
joi                 10.6.0  10.6.0  13.3.0  fxa-oauth-server
load-grunt-tasks     3.5.2   3.5.2   4.0.0  fxa-oauth-server
mocha                3.5.3   3.5.3   5.1.1  fxa-oauth-server
newrelic             2.2.2   2.2.2   4.1.1  fxa-oauth-server
nock                 8.2.2   8.2.2   9.2.6  fxa-oauth-server
nyc                 11.0.2  11.0.2  11.8.0  fxa-oauth-server
proxyquire           1.8.0   1.8.0   2.0.1  fxa-oauth-server
raven                2.2.1   2.2.1   2.6.2  fxa-oauth-server
request             2.83.0  2.86.0  2.86.0  fxa-oauth-server
sinon               1.17.7  1.17.7   5.0.7  fxa-oauth-server

**Comment by rfk** [comment]
🗡 ; we'll detect this again using auth-server linting mechanisms
