### ISSUE TITLE
Update to bluebird 3

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#570]
During the all-hands we found that bluebird 2 doesn't work so well with Hapi 17.

Let's clean up the old bluebird usage and use native Promises before we upgrade

**Comment by philbooth** [comment]
> native Promises

😞

**Comment by philbooth** [comment]
Do we know if bluebird 3.x has the same issue?

**Comment by vladikoff** [comment]
>> native Promises

> 😞

What's the concern besides the `recursive`[1] footgun? If we cannot use the native APIs then it is concerning.


[1] - https://alexn.org/blog/2017/10/11/javascript-promise-leaks-memory.html

**Comment by vladikoff** [comment]
> Do we know if bluebird 3.x has the same issue?

It does not

**Comment by vladikoff** [comment]
> Update to bluebird 3 

Pivoted the strategy, I think back in the day we had a long term to drop bluebird one day, but seems like it's just too good.

@deeptibaghel let's update to bluebird 3 instead, then should help us with the Hapi 17 strategy

**Comment by philbooth** [comment]
> What's the concern besides the `recursive`[1] footgun?

That's my only concern fwiw.

> Pivoted the strategy

Splendid!

**Comment by shane-tomlinson** [comment]
> > Pivoted the strategy
> Splendid!

If the content server ever has more than one place where promises are used, let's use Bluebird@3 there too.
