### ISSUE TITLE
Use bearer token as signing cred

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-oauth-server#7]
Current: Imagine foo.com gets a token for Alice, with permissions `read profile, write bankaccount`. When making a request to the profile server, passing this token to it also happens to give the profile server permission to write to bankaccount of Alice.

Instead, it'd be great if instead of passing the token to attached services, the token was used to sign a request and append the hmac. The oauth server could verify the hmac, without the attached service ever getting their robotic hands on the sacred token.

**Comment by shane-tomlinson** [comment]
Closing until we come back to this. The history is here.
